"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['--iconfile']
OPTIONS = {
    'packages':[
        'datetime',
        'PIL',
        'io',
        'os',
        'pydub',
        'speech_recognition',
        'tkinter'
    ],
    'plist': {
        'CFBundleName': 'SpeechToText'
    },
    'iconfile': '/Users/ethan/simple_stt/stt_icon.icns'
}

setup(
    app=APP,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    #include_package_data=True
    #package_data={'static':['*']}
)

